### ISSUE TITLE
Handling multiple triggering sources with different JSON data

### ISSUE THREAD

**Issue by hepcat72** [webhookrelay/node-red-contrib-webhookrelay#3]
First, thanks for webhookrelay.  I really like it.  I'm using it for personal/home automation.

I have a question and a possible feature request.

First, if I include a webhookrelay node connected to the same public endpoint in 2 different node-red flows, are 2 separate websockets maintained or is one socket per endpoint maintained?  I'm just curious if there's more overhead in terms of sockets if I put a webhookrelay node using the same endpoint in different flows.

I set up my first flow which I call automatically from an app on my phone based on location.  It has an immutable JSON structure.  I can change a value or 2, but not the variable names.  I'm planning on creating another flow that gets its webhook POSTs from a different source.  If I set up a second flow which uses the same webhookrelay endpoint but is called from a different source (e.g. IFTTT) and has a different JSON file structure, is it possible to inject a variable into the JSON based on where the webhook is coming from?

**Comment by rusenask** [comment]
Hi, glad to hear it's useful for you! 

Regarding nodes and separate connections - yes, each node will create a websocket but it's okay, they are very lightweight and even having several open will never approach the amount of data passed when you open a typical web page :) 

In my workflows I have several webhookrelay nodes always active. I also use "switch" node to separate incoming webhooks based on their webhookrelay bucket names:

![image](https://user-images.githubusercontent.com/9080105/56771373-589a7a00-67ae-11e9-9801-a3e69401e25e.png)

Then, based on topic/bucket name you divert flow into a nodes that decode different JSON structures.

You can also detect which input received it by inspecting payload.meta.input_name field:

![image](https://user-images.githubusercontent.com/9080105/56771339-3c96d880-67ae-11e9-8b5e-ea61af377fe7.png)

Does this sound helpful to you? I imagine that for a second flow you can either inspect the bucket or input names, that should be enough :) Also, you can also check request headers, usually they are different when dispatched by multiple separate applications.

**Comment by hepcat72** [comment]
Well, I'm embarrassed to say I'm trying to get by with the 1 free bucket/input, so I guess if there's no way to tell where a POST came from (coming into webhookrelay and relayed to my nodered instance), I'll have to handle using different/missing JSON variables.

**Comment by rusenask** [comment]
No worries, I will bump up your limits later today when I have a chance :)
